import React from "react";
import { Container, Row, Col } from "react-bootstrap";

const About = () => {
  return (
    <>
        <Container style={{marginTop:'50px'}}>
            <h1>Qui sommes-nous ?</h1>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit deleniti sapiente, ab libero vel eaque sit, officiis dolorum exercitationem vitae omnis minus perferendis consequuntur quae dolorem provident? Hic voluptatem optio molestiae, eius atque, amet deserunt libero ipsa, error voluptatibus ex sed nisi. Dolorum ipsum quod minima eaque vero iste veniam reprehenderit obcaecati ea dolorem praesentium, eius aut ipsa consectetur. Voluptatum nesciunt et eaque voluptatem, inventore nam natus aliquam sed, molestiae placeat explicabo? Mollitia sit facere libero, nemo accusamus commodi laboriosam, a, repudiandae qui maiores aperiam voluptate repellat impedit illo dignissimos eaque culpa minus maxime delectus repellendus vitae neque? Nobis vel iure, reiciendis cupiditate adipisci mollitia consectetur expedita quisquam enim! Sit dolor commodi ullam minus, est, fuga eveniet omnis, quaerat excepturi praesentium aperiam! Praesentium nostrum inventore repellendus, fugit quod, quas ducimus corporis maiores itaque totam facilis magni a blanditiis dolorum voluptatum obcaecati animi harum. Similique asperiores cum fugiat adipisci, placeat ex deserunt iure, aliquid quod totam quidem illo iste dignissimos dolores pariatur natus fuga. Quidem velit error sed veniam labore nam fugiat est nisi, autem necessitatibus ipsa illo sint aut consequatur temporibus obcaecati ipsum quod exercitationem accusantium. Natus numquam perspiciatis consequatur nihil quis dolorem est cupiditate in soluta, repellat amet aliquid.</p>
            <h2>Notre spécialité</h2>
            <Row>
                <Col>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta, dolore! Itaque assumenda alias deleniti eligendi reprehenderit at magni ipsam repudiandae voluptates quo inventore numquam, similique explicabo animi et cum iste nisi provident? Aut voluptas dignissimos nemo delectus, sint aspernatur id veniam dolorum nam quam! Perspiciatis nulla qui quas laudantium consectetur voluptatum molestiae? Deserunt perferendis eius porro! Optio nostrum animi unde fuga totam consectetur commodi doloribus nemo aliquam minima at labore error repudiandae ad dolorum, iure cupiditate earum soluta neque explicabo ea officiis dolores deserunt. Veritatis quibusdam vero obcaecati. Vel adipisci eligendi inventore facere natus amet voluptate, fugiat minima tempore recusandae magnam qui esse possimus itaque eaque vero laborum molestiae dicta ab exercitationem ipsam corrupti illum eum provident. Modi, minima atque! Amet ratione delectus sed blanditiis omnis consequuntur perferendis assumenda. Quod incidunt perspiciatis itaque rerum maxime, maiores corrupti accusamus animi recusandae aliquam, sed distinctio? Alias eveniet asperiores harum, quaerat at, vero velit magnam hic aliquam ipsam exercitationem, dicta architecto veritatis molestiae? Est voluptatum voluptatibus placeat repellendus accusantium error maxime reprehenderit iusto voluptatem deleniti quisquam deserunt sit sequi, itaque architecto harum nobis enim, distinctio neque ut minus quis ullam. Nostrum optio expedita soluta voluptate fugit fuga atque blanditiis vel minima, obcaecati deleniti!</p>
                </Col>
                <Col md={6}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius quod numquam quas dolor, quis sed tempora soluta, enim nesciunt obcaecati necessitatibus assumenda, tenetur pariatur ab facere ipsum placeat optio. Officia cupiditate alias dolorem harum quae, nesciunt facilis aspernatur totam quod blanditiis culpa fugit. Ullam illo, assumenda vitae mollitia cupiditate saepe rem id explicabo consequatur neque asperiores! Quos voluptas corrupti hic fugiat. Quia accusamus voluptate dolor, minima quaerat incidunt voluptates possimus est aliquid eos consectetur consequuntur sunt, eum enim voluptatum atque veritatis dicta. Accusamus, ullam vero. Facere fuga ut voluptas quis amet repudiandae obcaecati rerum doloribus dolorem, commodi saepe consectetur vero similique. Porro suscipit accusamus quasi atque excepturi voluptatibus ducimus earum id velit hic modi esse, praesentium quae odio magni veritatis commodi eius aliquid maxime? Id sint atque soluta tenetur eligendi aliquid delectus adipisci minima magnam inventore architecto porro deserunt, expedita illum aliquam in ducimus incidunt. Aliquam delectus ad consequuntur minus earum quisquam natus! Ratione dolorum iste incidunt reiciendis! Sit praesentium adipisci accusamus iure laboriosam, enim illum, similique ea amet consectetur natus doloremque. Dicta eligendi corrupti sapiente commodi nostrum omnis ex autem sunt, dolorum, est recusandae alias maiores repellendus minima ut deserunt magni odit reprehenderit tenetur ipsam animi eius quidem! Minus.</p>
                </Col>
            </Row>
            <Row>
                <h2>Le Chef</h2>
                <Col md={3}>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Architecto sit maxime voluptas pariatur quasi est iste maiores et mollitia atque laboriosam ipsum quas dolores ut vero, debitis culpa animi, nam autem officiis, porro unde. Minus facilis amet neque debitis, quia accusamus placeat fugiat explicabo eaque! Cum iste nobis aut delectus nulla voluptates dicta tempora in dignissimos quisquam voluptate, fugiat doloribus aliquam inventore officiis! Quas voluptas ea illum magnam? Sint illum, adipisci doloribus ullam debitis odio aliquid accusamus iusto praesentium nesciunt voluptatum saepe esse ad! Recusandae fugiat sequi ullam, sapiente rerum molestiae quam fuga, totam minus deserunt eaque, nesciunt eum dignissimos?</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eum voluptates placeat molestiae reprehenderit voluptate. Eaque totam unde, accusamus repellat minus, illo suscipit non eius labore in molestiae debitis. Rerum quos vero voluptate distinctio quisquam, quibusdam magnam doloribus aspernatur, ad facere exercitationem illum suscipit, beatae qui vitae repellat ipsa quo nemo molestiae temporibus deleniti illo odit. Autem accusamus aliquam reprehenderit consequatur consectetur quidem illo necessitatibus vero cupiditate? Recusandae, explicabo in. Officiis provident, magni quod, exercitationem consequatur labore doloremque aspernatur, cum illo dolore assumenda accusantium suscipit placeat minima ipsam omnis reprehenderit aliquid! Quisquam nemo quia officia molestias. Unde mollitia dolores dolor repellat.</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nobis ullam nisi voluptatibus maiores assumenda corporis esse delectus sunt blanditiis itaque asperiores quo suscipit, quod minus maxime nam repellendus, veritatis vitae consequatur ut expedita sed? Earum, eos impedit dolorem aut quaerat quos magnam eius dolore necessitatibus itaque commodi provident et quis labore accusamus hic quibusdam odio adipisci velit assumenda neque quod possimus non veritatis. Veniam quia numquam quo sit quidem laboriosam aliquid, recusandae distinctio quod repellat aliquam vero modi officia ipsa? Ipsam minima molestiae a soluta libero reiciendis porro deserunt velit, delectus odit dolorum, laborum commodi, dolorem consectetur optio necessitatibus.</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid ratione corrupti libero iste nihil, nostrum, temporibus ea laborum natus repellat dolorem sunt molestias quos sit, beatae tempore veritatis optio numquam? Deserunt nisi beatae blanditiis repellat laudantium? Corrupti ipsum reprehenderit similique porro, doloribus error nesciunt, voluptatum labore doloremque adipisci eligendi voluptates nulla libero assumenda optio ullam aspernatur quis velit veniam dolorem quos dicta, autem dolore. Quisquam quibusdam at delectus? Aperiam delectus beatae, eius nostrum corrupti nobis soluta, molestiae labore atque repudiandae illo eveniet ad, eum quo ipsa. Nobis nulla, voluptate inventore ex quas sapiente mollitia sit fugiat provident velit, iste maxime.</p>
                </Col>
            </Row>
        </Container>
    </>
  );
};

export default About;